### ISSUE TITLE
Stopped working with June 2018

### ISSUE THREAD

**Issue by Jcamain** [alner/qsSimpleKPI#55]
I've just upgraded to June 2018 and this has just stopped working, FYI

**Comment by Ersgersg** [comment]
yes i confirm the same issue. looking in the console we can see : 

qvangular-injector-require-plugin.js:27 This plugin is unsupported and deprecated, use instead angularjs $injector
40.8e64cfe8993264ccfc07.js:576 Error in extension 'extensions/qsSimpleKPI/qsSimpleKPI': Can not use internal module 'objects.utils/number-formatter'.

**Comment by MohammadHatamleh** [comment]
Hi All
Yes I have the same issue anyone fix it?

**Comment by alner** [comment]
Do you use latest build?

**Comment by MohammadHatamleh** [comment]
Hi Alner
what do you mean the last build? I tried the latest version of the ext but with same issue

**Comment by lachlanwwells** [comment]
Stopped working for us too, June 2018. Latest version
![image](https://user-images.githubusercontent.com/26990992/42193628-fe41e640-7eb2-11e8-8cfc-a37b76387c75.png)

**Comment by alner** [comment]
Try to clear or disable your browser cache. The latest version of qsSimpleKPI supports Qlik Sense June 2018.

**Comment by Ersgersg** [comment]
I confirm issue is fixed by using latest build

**Comment by oihanaro** [comment]
Hello, we used the property of link sheet and it doesn't work with Qlik Sense June 2018., we are using the latest version of qsSimpleKPI. ¿there is any posibility of solving it?
Thanks

**Comment by joaopaulodelconti** [comment]
I did the same of @oihanaro and is not working with June 2018 version.

**Comment by alner** [comment]
Navigation to a sheet has been fixed. Please download and use the latest build.

**Comment by joaopaulodelconti** [comment]
Thanks @alner , now it's working perfectly.

**Comment by lovekeshsa** [comment]
Hi Alner, 

Just to inform the navigation is still not working in the browser. Could you please look at this as well.

**Comment by lovekeshsa** [comment]
@alner, or if there is any other solution you can let me know, that will be great

**Comment by alner** [comment]
@lovekeshsa Did you try the latest build? Navigation has been fixed in the latest build. Please try to clear your browser cache also (sometimes it caches old javascript code).

**Comment by lovekeshsa** [comment]
Thanks @alner It worked after deleting the cache memory. Thanks for the help :)

**Comment by Toskache** [comment]
Hi Alner,
qsSimpleKPI worked perfectly with my previous version of QlikSense Desktop. But with the June-Update it stopped working. I am using the current build but the Console give me:

"This plugin is unsupported and deprecated, use instead angularjs $injector" and
GET http://localhost:4848/resources/objects.utils/number-formatter.js 404 (Not Found)
Error in extension 'extensions/qsSimpleKPI/qsSimpleKPI': Can not use internal module 
Error: Script error for "objects.utils/number-formatter", needed by: Extensions/qsSimpleKPI/qsSimpleKPI(…)

Any ideas?
Thanks in advance
